### ISSUE TITLE
Restructure README

### ISSUE THREAD

**Issue by moxley** [vic/params#27]
In my opinion, the README contains too much back story that you have to wade through before getting to the basic usage of the package. _Everybody_ is interested in the basic usage, but only some people are interested in the back story. I suggest moving the "Usage" section to near the top of the document.

I'd be happy to make this into a PR.

**Comment by vic** [comment]
Hey, sure, send that PR 👍

**Comment by moxley** [comment]
Ok, we'll see. The direction we're going with regards to `params` has changed. We're not using it now. I'll close this issue for now.
