### ISSUE TITLE
Release latest version to hex

### ISSUE THREAD

**Issue by mawie81** [vic/params#32]
Hi,

i'd like to use #30 in our codebase. For this it would be great to have a new release on hex.
The last one there is 2.1.1 which is from january 2019.

Thanks in advance.

**Comment by vic** [comment]
Hello,

Sorry for the very late reply, I've just released `2.2.0` to https://hex.pm/packages/params

**Comment by vic** [comment]
Also, I'm not currently an active Elixir user (I'm doing mostly Scala nowadays) but if you find this library useful for your current projects and are willing to devote an small amount of time to keep it maintained, I'd happily add you as contributor so you can merge changes and push releases as you see fit.

Just hand me you hex.pm username if you agree.

Cheers :)
