### ISSUE TITLE
:atom not included in the types

### ISSUE THREAD

**Issue by Ziinc** [vic/params#36]
Hi, big fan of this library for typecasting.

I notice that the atom type is not provided and raises an invalid type error, is this expected behaviour? Was hoping to cast strings to atoms automatically.

```
(ArgumentError) invalid or unknown type :atom for field :status

Stacktrace:
  │ (ecto 3.7.1) lib/ecto/schema.ex:2201: Ecto.Schema.check_field_type!/4
  │ (ecto 3.7.1) lib/ecto/schema.ex:1881: Ecto.Schema.__field__/4
  │ (stdlib 3.16.1) erl_eval.erl:685: :erl_eval.do_apply/6
  │ (stdlib 3.16.1) erl_eval.erl:123: :erl_eval.exprs/5
  │ (stdlib 3.16.1) erl_eval.erl:919: :erl_eval.try_clauses/8
  │ (stdlib 3.16.1) erl_eval.erl:123: :erl_eval.exprs/5Elixir
```

**Comment by lasseebert** [comment]
I usually use EctoEnum to define custom enum types (of atoms). The problem of just converting any input string to an atom, is that an attacker can fill your memory with atoms.

**Comment by Ziinc** [comment]
@lasseebert yes, I was able to figure out the syntax that Params accepted.

For reference sake:
```elixir
my_field: [field: Ecto.Enum, values: [:unmarked, :pending, :cleared], default: :unmarked]
```
