### ISSUE TITLE
Params.to_map behaviour for missing fields.

### ISSUE THREAD

**Issue by lasseebert** [vic/params#9]
Both `to_map` and `data` have the behaviour that it's not possible to see if `nil` was submitted for a field or if that field was not submitted at all.

It makes sense that `data` behaves that way, since it returns a struct. But with `to_map`, I would expect it to use the schema as whitelist and not add extra fields unless `default` is used.

Maybe this should be a different function than `to_map`?

My usecase is an API endpoint that can update a resource. Something like this:

```
defmodule MyAPIEndpoint do
  defmodule MyParams do
    use Params.Schema, %{
      id!: :integer,
      name: string,
      owner_id: :integer
    }
  end

  def call(params) do
    changeset = MyParams.from(params)
    if changeset.valid? do
      attributes = Params.to_map(changeset)
      MyRepo.update_attributes(attributes)
    end
  end
end
```

So I want to update only the submitted keys. In this case it should be possible to update `owner_id` to the value `nil`.

Again, I will be happy to help with the implementation. Just wanted your oppinion before getting started ;)

**Comment by vic** [comment]
Hey @lasseebert,

Definitely your use case seems valid to me, there should be a way to determine if some value was given on the request or completely missed. And as you mention I think the behaviour of `to_map` has to change, having `nil` values only if the user explicitly sent nil for that field or if the developer specified a default nil value for it.  Please go ahead implementing it.

I've just added you as collaborator so you can directly merge things or send PR if you want some code review. Also merged `ecto-2.x` branch into master as I think we'll be adding more features on it and `ecto-1.x` branch will be kept behind.

Thanks again! :)

**Comment by vic** [comment]
Oh, just to make it clear, I don't think we need a separate method besides `to_map`, so feel free to change it as you said.

**Comment by vic** [comment]
We should update the documentation after this, IIRC it still mentions the old `changes` function. And we should mention the new behaviour of `to_map` and how it contrasts with `data`.

**Comment by lasseebert** [comment]
Thanks for making me a collaborator :)
I'll make the changes to `to_map` as discussed above.
